CREATE TABLE TASKS (                                          TaskID        INTEGER NOT NULL
GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1), ScheduledType INT, Schedule VARCHAR(20), TypeID INT, TYPE VARCHAR(20), startDate TIMESTAMP, nextDate TIMESTAMP, CONSTRAINT TASK_PK PRIMARY KEY (TaskID));
CREATE TABLE PARTIALTASKINCLUDES (TaskID INT, TablesSpaces INT, INIT SMALLINT, DATAFILES SMALLINT, CONTROLFILE SMALLINT, ARCHIVELOGS SMALLINT, CONSTRAINT PTI_FK FOREIGN KEY (TaskID) REFERENCES TASKS);
CREATE TABLE TABLESPACE (TaskID INTEGER, TableSpaceName VARCHAR(128), CONSTRAINT TABLESPACE_FK FOREIGN KEY (TaskID) REFERENCES TASKS);
CREATE TABLE DATAFILE (TaskID INTEGER, DataFileName VARCHAR(128), CONSTRAINT DATAFILE_FK FOREIGN KEY (TaskID) REFERENCES TASKS);